import os
import time
import pandas as pd
from datasets import Dataset

# --- THE "MONKEY PATCH" FIX FOR THE RAGAS BUG ---
import sys
import types
# We trick Python into thinking the VertexAI module exists so Ragas stops crashing.
dummy_vertex = types.ModuleType('langchain_community.chat_models.vertexai')
dummy_vertex.ChatVertexAI = type('ChatVertexAI', (object,), {}) 
sys.modules['langchain_community.chat_models.vertexai'] = dummy_vertex
# ------------------------------------------------

from ragas import evaluate
from ragas.metrics import faithfulness, answer_relevancy, context_precision

from graph import app as rag_pipeline
from nodes import llm as groq_llm
from nodes import embeddings as local_embeddings

def run_evaluation():
    print("🧪 --- STARTING RAGAS EVALUATION ---")
    print("Initializing test dataset...\n")
    
    # 1. Define our test set (Questions and Ground Truth answers)
    # We keep this small (2 questions) so we don't hit Groq's free-tier rate limits!
    test_questions = [
        "What is the mathematical formula for the attention mechanism?",
        "What problem do Physics Informed Neural Networks (PINNs) solve?"
    ]
    
    ground_truths = [
        "The attention mechanism formula is Attention(Q, K, V) = softmax(QK^T / sqrt(d_k))V.",
        "PINNs solve supervised learning tasks while respecting physical laws described by nonlinear partial differential equations."
    ]
    
    answers = []
    contexts = []
    
    # 2. Run each question through YOUR LangGraph pipeline
    for i, question in enumerate(test_questions):
        print(f"🔄 Processing Question {i+1}/{len(test_questions)}: '{question}'")
        
        # Invoke your graph
        inputs = {"question": question}
        result = rag_pipeline.invoke(inputs)
        
        # Extract the final answer generated by your AI
        generated_answer = result.get("generation", "Error: No answer generated")
        answers.append(generated_answer)
        
        # Extract the raw text chunks retrieved by ChromaDB
        retrieved_docs = result.get("documents", [])
        doc_texts = [doc.page_content for doc in retrieved_docs]
        contexts.append(doc_texts)
        
        # Brief pause to respect Groq's rate limits
        time.sleep(2)

    # 3. Format the data exactly how RAGAS expects it (HuggingFace Dataset format)
    data = {
        "question": test_questions,
        "answer": answers,
        "contexts": contexts,
        "ground_truth": ground_truths
    }
    
    dataset = Dataset.from_dict(data)
    
    print("\n📊 Data collection complete! Running RAGAS Metrics...")
    print("(Groq is now grading the answers. This takes a few moments...)\n")
    
    # 4. Run the RAGAS Evaluation
    # We pass your Groq LLM and HuggingFace embeddings so it doesn't try to use OpenAI
    evaluation_results = evaluate(
        dataset=dataset,
        metrics=[
            faithfulness,       # Checks for hallucinations
            answer_relevancy,   # Checks if the question was answered
            context_precision   # Checks if ChromaDB fetched good data
        ],
        llm=groq_llm,
        embeddings=local_embeddings,
        raise_exceptions=False
    )
    
    # 5. Print the gorgeous scorecard
    print("\n" + "="*50)
    print("🏆 RAGAS EVALUATION SCORECARD 🏆")
    print("="*50)
    
    # Convert the results to a Pandas DataFrame for a beautiful table printout
    df = evaluation_results.to_pandas()
    
    # Safely get means (in case RAGAS changed metric names)
    f_score = df['faithfulness'].mean() if 'faithfulness' in df.columns else 0.0
    ar_score = df['answer_relevancy'].mean() if 'answer_relevancy' in df.columns else 0.0
    cp_score = df['context_precision'].mean() if 'context_precision' in df.columns else 0.0
    
    # Print the overall averages
    print(f"Overall Faithfulness:      {f_score:.2f} / 1.0")
    print(f"Overall Answer Relevancy:  {ar_score:.2f} / 1.0")
    print(f"Overall Context Precision: {cp_score:.2f} / 1.0")
    print("="*50)
    
    print("\nDetailed Breakdown per Question:")
    # RAGAS recently changed column names (e.g., 'question' -> 'user_input').
    # We dynamically grab the columns that exist to prevent crashes!
    cols = [c for c in ['question', 'user_input', 'faithfulness', 'answer_relevancy', 'context_precision'] if c in df.columns]
    print(df[cols])

if __name__ == "__main__":
    run_evaluation()